/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const OverviewLazyImport = createFileRoute('/overview')()
const IndexLazyImport = createFileRoute('/')()
const QueryDetailsIdLazyImport = createFileRoute('/query/details/$id')()

// Create/Update Routes

const OverviewLazyRoute = OverviewLazyImport.update({
  path: '/overview',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/overview.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const QueryDetailsIdLazyRoute = QueryDetailsIdLazyImport.update({
  path: '/query/details/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/query/details.$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/overview': {
      preLoaderRoute: typeof OverviewLazyImport
      parentRoute: typeof rootRoute
    }
    '/query/details/$id': {
      preLoaderRoute: typeof QueryDetailsIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  OverviewLazyRoute,
  QueryDetailsIdLazyRoute,
])

/* prettier-ignore-end */
